config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

  resources :topics, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
      collection do
        post :confirm
    end
  end

  resources :topics do
   resources :comments
    post :confirm, on: :collection
   end

 resources :conversations do
  resources :messages
   end

  

  root 'top#index'

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
 end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user

  # CommentモデルのAssociationを設定
  has_many :comments, dependent: :destroy

  mount_uploader :picture , PictureUploader

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :authenticate_user!

  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all
    respond_to do |format|
    format.html
    format.js
  end

  end

  def new
  	if params[:back]
     @topic = Topic.new(topic_params)
     else
      @topic = Topic.new
    end
  end


  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

     if @topic.save
       redirect_to topics_path, notice: "投稿しました！"
       NoticeMailer.sendmail_topic(@topic).deliver

     else
      render 'new'

    # Topic.create(topic_params)
    # redirect_to topics_path
    # redirect_to topics_path, notice: "投稿しました！"
    end
  end

  def edit
     @topic = Topic.find(params[:id])

  end

  def update
    @topic = Topic.find(params[:id])
    @topic.update(topic_params)
    redirect_to topics_path, notice: "投稿しました！"
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path, notice: "投稿しました！"
  end

  def confirm
    @topic = Topic.new(topic_params)
    render :new if @topic.invalid?

  end

  # showアククションを定義します。入力フォームと一覧を表示するためインスタンスを2つ生成します。
  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
  end


    private
    def topic_params
      params.require(:topic).permit(:picture, :content)
    end

      # idをキーとして値を取得するメソッド
    def set_topic
      @topic = Topic.find(params[:id])
    end


 end

app/helpers/topics_helper.rb
module TopicsHelper
 def choose_new_or_edit
  if action_name == 'new' || action_name == 'confirm'
   confirm_topics_path
   elsif action_name == 'edit'
    topic_path
   end
  end

end

app/views/topics/_form.html.erb
<%= form_for(@topic, url: choose_new_or_edit) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.file_field :picture %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>

  <% end %>

<%= link_to "topic一覧画面にもどる", topics_path %>

app/views/topics/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@topic) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>

  <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>タイトル:<%= @topic.title %></p>
  <p>本文:<%= @topic.content %></p>
  <%= f.submit "登録する" %>
<% end %>

<%= form_for(@topic, url: new_topic_path, method: 'get') do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>

app/views/topics/edit.html.erb
<p id="notice"><%= notice %></p>
<% if @topic.errors.any? %>
     <div id="error_explanation">
      <!-- バリデーションエラーの件数表示   -->
      <h2><%= @topic.errors.count %>件のエラーがあります</h2>

       <ul>
        <% @topic.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
         <% end %>
       </ul>
       </div>
       <% end %>
   <div class="show">
   <%= link_to "一覧" , topics_path, class: 'btn btn-default' %>
   </div>

  <div class="container">
  <div class="col-md-8 col-md-offset-2">
   <%= form_for(@topic) do |f| %>
     <div class="row">
     <%= image_tag(@topic.picture) %>
       <%= f.file_field :picture %>
    </div>
  <div class="row">
    <%= f.text_field :content, class: 'btn btn-default' %>
  </div>


    <%= f.submit class: 'btn btn-default edit' %>
 </div>
 <% end %>
</div>
</div>

app/views/topics/index.html.erb
<div class="container">
 <div class="wrapper col-md-8 col-md-offset-2">

 <%= link_to "投稿する", new_topic_path, class: 'btn btn-default post' %>
 <h2>Topic一覧</h2>

<% @topics.each do |topic| %>
 <div class="row">
   <!-- ブログのタイトルにlink_toでリンクを設定します。 -->
        <%= link_to topic_path(topic) do %>
        <h4><strong><%= topic.title %></strong></h4>
        <% end %>

<!-- <form> -->
  <%= image_tag (topic.picture_url) %><br>
  <!-- <div class="comment"> -->
   <div class="text">
   <%= topic.content %><br>
   </div>
     <%= link_to "コメントを書く", topic_path(topic) %>

   
   <div class="profile">
   <div class="profile_img">
    <%= profile_img(topic.user) %>
    </div>
    <div class="user_name">
    <%= topic.user.name %> が投稿しました
     <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      <i class="fa fa-trash" aria-hidden="true"></i>
   </div>
   </div>
  
   
   <!-- <div class="edit_d"> -->
    <%= link_to "編集" , edit_topic_path(topic.id), class: 'btn btn-default'%>
  
  <%= link_to "削除" , topic_path(topic.id), method: :delete, data: { confirm: '本当に削除していいですか？'},class: 'btn btn-default' %>
  <!-- </div> -->

  </div>
 <% end %>
 <!-- </form> -->
 </div>
</div>

app/views/topics/new.html.erb
<p id="notice"><%= notice %></p>
<% if @topic.errors.any? %>
     <div id="error_explanation">
      <!-- バリデーションエラーの件数表示   -->
      <h2><%= @topic.errors.count %>件のエラーがあります</h2>

       <ul>
        <% @topic.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
         <% end %>
       </ul>
       </div>
       <% end %>
  <div class="container">
  <div class="col-md-8 col-md-offset-2">
   <%= form_for(@topic) do |f| %>
     <div class="row">
     <%= f.file_field :picture %>
    </div>
  <div class="row">
    <%= f.text_field :content, class: 'btn btn-default' %>
  </div>


    <div class="submit">
    <%= f.submit class: 'btn btn-default push' %>
    </div>
 </div>
 <% end %>

<div class="back">
 <%= link_to "一覧に戻る" , topics_path %>
</div>

</div>
</div>

app/views/topics/show.html.erb
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="topic-text">
      <!-- <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @topic.title %></p> -->
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @topic.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <% if current_user.id == @topic.user_id %>
      <%= link_to '編集', edit_topic_path(@topic) %> |
    <% end %>
    <%= link_to '戻る', topics_path %>
  </div>
</div>