config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

  resources :topics, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
      collection do
        post :confirm
    end
  end

  resources :topics do
   resources :comments
    post :confirm, on: :collection
   end

 resources :conversations do
  resources :messages
   end

  

  root 'top#index'

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
 end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :content, presence:true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   def new
       if params[:back]
        @contact = Contact.new(contact_params)
       else
        @contact = Contact.new
       end
   end
   
   def create
      @contact = Contact.create(contact_params)
      if @contact.save
       redirect_to root_path, notice: "お問い合わせが完了しました"
       # NoticeMailer.sendmail_contact(@contact).deliver
     #   render 'new'
      end
   end
   
   def confirm
    @contact = Contact.new(contact_params)
    render :new if @contact.invalid?
   end
       
  private
   def contact_params
     params.require(:contact).permit(:name, :email, :content)
   end
 
 end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="container">
 <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
 <%= f.hidden_field :name %>
 <%= f.hidden_field :email %>
 <%= f.hidden_field :content %>
 
 <p>名前:<%= @contact.name %></p>
 <p>メールアドレス:<%= @contact.email %></p>
 <p>内容:<%= @contact.content %></p>
  <%= f.submit "送信する", class: 'btn btn-primary btn-block' %>
 <% end %>
 
  <%= form_for(@contact,url: new_contact_path, method: 'get') do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %><br>
  <%= link_to "topic一覧へ戻る", topics_path %>

  <% end %>

  </div>
 </div>
 
 

app/views/contacts/new.html.erb
<div class="container">
 <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<p id="notice"><%= notice %></p>

<h1>お問い合わせ</h1>

<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
 <% if @contact.errors.any? %>
 <div id="error_explanation">
  <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @contact.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
     <% end %>
  </ul>
 </div>
  <% end %>
 <%= f.label :name %>
 <%= f.text_field :name, class: 'form-control' %>
 <br>
 <%= f.label :email %>
 <%= f.text_field :email, class: 'form-control' %>
 <br>
 <%= f.label :content %>
 <%= f.text_field :content, class: 'form-control' %>
 <br>
  <%= f.submit "送信", class: 'btn btn-primary btn-block'%><br>
  <%= link_to "topic一覧へ戻る", topics_path %>

 <% end %>
 
 </div>
   
 </div>