config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

  resources :topics, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
      collection do
        post :confirm
    end
  end

  resources :topics do
   resources :comments
    post :confirm, on: :collection
   end

 resources :conversations do
  resources :messages
   end

  

  root 'top#index'

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
 end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Face</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
  <header>
  <div class="face">facebook</div>
 <% if user_signed_in? %>
 <div class="log_in">
 <ul>
 <li><%= link_to 'マイページ', edit_user_registration_path %></li>
  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
  <li><%= link_to 'ユーザー一覧', users_path if user_signed_in? %></li>
  <li><%= link_to "メッセージ", conversations_path %></li>


 <% else %>
  <li><%= link_to 'ログイン', new_user_session_path  %></li>
  <li><%= link_to 'サインアップ', new_user_registration_path %></li>
  </ul>
  </div>

 <% end %>

 </header>
 <p class="flash"><%= notice %><%= alert %></p> 
   <%= yield %>
  <footer>
    <div class="contact"><%= link_to "お問い合わせ" , new_contact_path %></div>
  </footer>
 </body>
</html>